### ISSUE TITLE
test_base_scenario

### ISSUE THREAD

**Issue by LucienTriail** [Pyosch/vpplib#41]
Hello, i get this error when launching test_base_scenario.py .
Here is the full traceback : 

C:\Users\smeca\.pyenv\pyenv-win\versions\3.9.4\lib\site-packages\pvlib\pvsystem.py:478: pvlibDeprecationWarning: temperature_model_parameters, racking_model, and module_type are not specified. Reverting to deprecated default: SAPM cell temperature model parameters for a glass/glass module in open racking. In v0.9, temperature_model_parameters or a valid combination of racking_model and module_type will be required.
  warnings.warn(
  0%|                                                                                                                                                      | 0/96 [00:00<?, ?it/s] 
Traceback (most recent call last):
  File "C:\Users\smeca\Documents\vpplibclone\vpplib\test_base_scenario.py", line 412, in <module>
    net_dict = operator.run_base_scenario(baseload)
  File "C:\Users\smeca\Documents\vpplibclone\vpplib\vpplib\operator.py", line 320, in run_base_scenario
    res_loads.loc[idx][bus].item()
AttributeError: 'float' object has no attribute 'item'

Thanks and good work.

**Comment by zypher22** [comment]
Pyosch,

First thanks for sharing some great content.  I did get the same error as Lucien after cloning the dev branch. Haven't tried the master branch since it was 137 commits behind the dev branch.  

Traceback (most recent call last):
  File "test_base_scenario.py", line 412, in <module>
    net_dict = operator.run_base_scenario(baseload)
  File "<<PATH TO DIR>>\vpplib\vpplib\operator.py", line 320, in run_base_scenario
    res_loads.loc[idx][bus].item()
AttributeError: 'float' object has no attribute 'item'.

Best,

SB

**Comment by Pyosch** [comment]
Hi Zypher,

ok, I'll have a look at it again and try to fix the issue. It might take a while though. Maybe try the master branch as well for the time being. 

Thanks for your interest in my library :)

Cheers Pyosch

**Comment by NormanSp1988** [comment]
Hi,
found a quick fix for this issue by commenting out the item()-function in line 316-320.
# run storage operation with residual load
state_of_charge, res_load = self.virtual_power_plant.components[
                            self.net.storage.loc[storage_at_bus].name.item()
                        ].operate_storage(
                            res_loads.loc[idx][bus]  # .item()
                        )

Cheers Norman

**Comment by Pyosch** [comment]
Hey Norman,

thanks for your contribution! I am currently working on updating the library, unfortunately pvlib pushed an update in the meantime too, which I have to take care of for everything to work. Hope I can deliver soon though.

Cheers
Sascha

**Comment by Pyosch** [comment]
Hey everyone,

I pushed changes to the dev branch (Yes, a lot). I included the bugfix of Norman (thanks again!) and hopefully it works for everyone now. If not, let me know. I will then also update the master and make a new release.

Cheers
Pyosch
